include:
  - board: nrfpill_10
    shield: settings_reset
  - board: nrfpill_10
    shield: sofle_numpad_left
  - board: nrfpill_10
    shield: sofle_numpad_right
  - board: nrfpill_10
    shield: sofle_numpad_num

